/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedMahasiswaDashboardRouteImport } from './routes/_authenticated/mahasiswa/dashboard'
import { Route as AuthenticatedMahasiswaJadwalRouteImport } from './routes/_authenticated/mahasiswa/jadwal'
import { Route as AuthenticatedMahasiswaKhsRouteImport } from './routes/_authenticated/mahasiswa/khs'
import { Route as AuthenticatedMahasiswaKrsRouteImport } from './routes/_authenticated/mahasiswa/krs'
import { Route as AuthenticatedMahasiswaPengumumanRouteImport } from './routes/_authenticated/mahasiswa/pengumuman'
import { Route as AuthenticatedMahasiswaProfilRouteImport } from './routes/_authenticated/mahasiswa/profil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMahasiswaDashboardRoute =
  AuthenticatedMahasiswaDashboardRouteImport.update({
    id: '/mahasiswa/dashboard',
    path: '/mahasiswa/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMahasiswaJadwalRoute =
  AuthenticatedMahasiswaJadwalRouteImport.update({
    id: '/mahasiswa/jadwal',
    path: '/mahasiswa/jadwal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMahasiswaKhsRoute =
  AuthenticatedMahasiswaKhsRouteImport.update({
    id: '/mahasiswa/khs',
    path: '/mahasiswa/khs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMahasiswaKrsRoute =
  AuthenticatedMahasiswaKrsRouteImport.update({
    id: '/mahasiswa/krs',
    path: '/mahasiswa/krs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMahasiswaPengumumanRoute =
  AuthenticatedMahasiswaPengumumanRouteImport.update({
    id: '/mahasiswa/pengumuman',
    path: '/mahasiswa/pengumuman',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMahasiswaProfilRoute =
  AuthenticatedMahasiswaProfilRouteImport.update({
    id: '/mahasiswa/profil',
    path: '/mahasiswa/profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mahasiswa/dashboard': typeof AuthenticatedMahasiswaDashboardRoute
  '/mahasiswa/jadwal': typeof AuthenticatedMahasiswaJadwalRoute
  '/mahasiswa/khs': typeof AuthenticatedMahasiswaKhsRoute
  '/mahasiswa/krs': typeof AuthenticatedMahasiswaKrsRoute
  '/mahasiswa/pengumuman': typeof AuthenticatedMahasiswaPengumumanRoute
  '/mahasiswa/profil': typeof AuthenticatedMahasiswaProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/mahasiswa/dashboard': typeof AuthenticatedMahasiswaDashboardRoute
  '/mahasiswa/jadwal': typeof AuthenticatedMahasiswaJadwalRoute
  '/mahasiswa/khs': typeof AuthenticatedMahasiswaKhsRoute
  '/mahasiswa/krs': typeof AuthenticatedMahasiswaKrsRoute
  '/mahasiswa/pengumuman': typeof AuthenticatedMahasiswaPengumumanRoute
  '/mahasiswa/profil': typeof AuthenticatedMahasiswaProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_authenticated/mahasiswa/dashboard': typeof AuthenticatedMahasiswaDashboardRoute
  '/_authenticated/mahasiswa/jadwal': typeof AuthenticatedMahasiswaJadwalRoute
  '/_authenticated/mahasiswa/khs': typeof AuthenticatedMahasiswaKhsRoute
  '/_authenticated/mahasiswa/krs': typeof AuthenticatedMahasiswaKrsRoute
  '/_authenticated/mahasiswa/pengumuman': typeof AuthenticatedMahasiswaPengumumanRoute
  '/_authenticated/mahasiswa/profil': typeof AuthenticatedMahasiswaProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/mahasiswa/dashboard'
    | '/mahasiswa/jadwal'
    | '/mahasiswa/khs'
    | '/mahasiswa/krs'
    | '/mahasiswa/pengumuman'
    | '/mahasiswa/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/mahasiswa/dashboard'
    | '/mahasiswa/jadwal'
    | '/mahasiswa/khs'
    | '/mahasiswa/krs'
    | '/mahasiswa/pengumuman'
    | '/mahasiswa/profil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/_authenticated/mahasiswa/dashboard'
    | '/_authenticated/mahasiswa/jadwal'
    | '/_authenticated/mahasiswa/khs'
    | '/_authenticated/mahasiswa/krs'
    | '/_authenticated/mahasiswa/pengumuman'
    | '/_authenticated/mahasiswa/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mahasiswa/dashboard': {
      id: '/_authenticated/mahasiswa/dashboard'
      path: '/mahasiswa/dashboard'
      fullPath: '/mahasiswa/dashboard'
      preLoaderRoute: typeof AuthenticatedMahasiswaDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mahasiswa/jadwal': {
      id: '/_authenticated/mahasiswa/jadwal'
      path: '/mahasiswa/jadwal'
      fullPath: '/mahasiswa/jadwal'
      preLoaderRoute: typeof AuthenticatedMahasiswaJadwalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mahasiswa/khs': {
      id: '/_authenticated/mahasiswa/khs'
      path: '/mahasiswa/khs'
      fullPath: '/mahasiswa/khs'
      preLoaderRoute: typeof AuthenticatedMahasiswaKhsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mahasiswa/krs': {
      id: '/_authenticated/mahasiswa/krs'
      path: '/mahasiswa/krs'
      fullPath: '/mahasiswa/krs'
      preLoaderRoute: typeof AuthenticatedMahasiswaKrsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mahasiswa/pengumuman': {
      id: '/_authenticated/mahasiswa/pengumuman'
      path: '/mahasiswa/pengumuman'
      fullPath: '/mahasiswa/pengumuman'
      preLoaderRoute: typeof AuthenticatedMahasiswaPengumumanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mahasiswa/profil': {
      id: '/_authenticated/mahasiswa/profil'
      path: '/mahasiswa/profil'
      fullPath: '/mahasiswa/profil'
      preLoaderRoute: typeof AuthenticatedMahasiswaProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMahasiswaDashboardRoute: typeof AuthenticatedMahasiswaDashboardRoute
  AuthenticatedMahasiswaJadwalRoute: typeof AuthenticatedMahasiswaJadwalRoute
  AuthenticatedMahasiswaKhsRoute: typeof AuthenticatedMahasiswaKhsRoute
  AuthenticatedMahasiswaKrsRoute: typeof AuthenticatedMahasiswaKrsRoute
  AuthenticatedMahasiswaPengumumanRoute: typeof AuthenticatedMahasiswaPengumumanRoute
  AuthenticatedMahasiswaProfilRoute: typeof AuthenticatedMahasiswaProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMahasiswaDashboardRoute: AuthenticatedMahasiswaDashboardRoute,
  AuthenticatedMahasiswaJadwalRoute: AuthenticatedMahasiswaJadwalRoute,
  AuthenticatedMahasiswaKhsRoute: AuthenticatedMahasiswaKhsRoute,
  AuthenticatedMahasiswaKrsRoute: AuthenticatedMahasiswaKrsRoute,
  AuthenticatedMahasiswaPengumumanRoute: AuthenticatedMahasiswaPengumumanRoute,
  AuthenticatedMahasiswaProfilRoute: AuthenticatedMahasiswaProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
